### PR TITLE
Add validation for inference ids in feedback.rs.

### PR DESCRIPTION
**Pull request by hk1997**
Adding validations to inference ids in feedback.rs by checking if the inference_id exisists in the table.

Updated integration tests and unit tests for testing

----

> [!IMPORTANT]
> Add inference ID validation in `feedback.rs` by checking their existence in the database and update tests accordingly.
> 
>   - **Validation**:
>     - Adds `get_target_identifier()` in `feedback.rs` to validate inference IDs against the database.
>     - Updates `write_comment()`, `write_demonstration()`, `write_float()`, and `write_boolean()` to use `get_target_identifier()` for validation.
>   - **Tests**:
>     - Updates unit tests in `feedback.rs` to cover new validation logic.
>     - Updates e2e tests in `feedback.rs` and `prometheus.rs` to test inference ID validation.
>   - **Misc**:
>     - Removes `get_function_name_from_inference_id()` as its functionality is replaced by `get_target_identifier()`.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=tensorzero%2Ftensorzero&utm_source=github&utm_medium=referral)<sup> for 705ac1c1c5c865d9f308181a628748a2b231b4dd. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by hk1997** [comment]
@virajmehta Ran into a lot of unintended behavior due to accidental rebase with the remote branch.
Deleted the earlier PR and raised this new PR with the requested changes.

**Review by virajmehta — DISMISSED** [review]
LGTM! Merry Christmas!

**Comment by virajmehta** [comment]
hey @hk1997 the linter is failing -- do you mind fixing it?

**Comment by hk1997** [comment]
@virajmehta Done resolved the lint errors.
Some function exceeded limit of 7 parameters, hence had to pass entire params variable instead of individual derived fields.

For consistency, I have updated all function interfaces to take params as input instead of individual fields derived from params for consistency.

Testing:
```
cargo clippy --all-targets --all-features -- -D warnings
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.27s
```

**Review by virajmehta — DISMISSED** [review]
LGTM

**Comment by virajmehta** [comment]
CI failed due to an annoying issue with secrets -- I have a fix in so we should just be able to merge from main in a little and try again

**Comment by virajmehta** [comment]
@hk1997 wow I guess we have more tests that I thought --> seems like now the python client tests in `clients/python/tests/test_client.py` are failing for similar reasons. Can you fix those too? Same issue as with Prometheus.

**Comment by hk1997** [comment]
Fixed the python client tests.
Good thing that this PR is setting up the ground work for episode validation PR.
Let's see if we get more test failures this time :p

**Review by virajmehta — APPROVED** [review]

**Comment by GabrielBianconi** [comment]
@hk1997 Looks like the Python linter failed!

Could you install "pre-commit" and run "pre-commit install" in the repo? That should run the linters etc. before each commit. And then for this case, run "ruff" like in the pre-commit config file?

Thanks!

**Comment by hk1997** [comment]
Completed running ```pre-commit run --all-files```

**Review by GabrielBianconi — APPROVED** [review]

**Comment by GabrielBianconi** [comment]
Fingers crossed...

**Comment by GabrielBianconi** [comment]
LFG thanks for the contribution @hk1997

**Pull request merged**
