### PR TITLE
Add simple home page

### LINKED ISSUE #595: Add a simple home page to the dashboard
We can start with a very simple home page. Later we'll add more information, metrics, etc.

CleanShot 2024-12-24 at 16 41 59@2x

https://v0.dev/chat/MjOv5O0HwV9?b=b_vwIdC2Dh2Dd

The sidebar (#594) should also show up.

### PR DESCRIPTION
**Pull request by ChetanXpro**
Closes #595 

----

> [!IMPORTANT]
> Adds a new home page with card components and updates routing to include this page.
> 
>   - **Home Page**:
>     - Adds a new home page in `index.tsx` with sections for "Observability" and "Optimization" using card components.
>     - Includes links to "Inferences", "Episodes", and "Fine-tuning" features.
>   - **Components**:
>     - Introduces `Card`, `CardHeader`, `CardTitle`, `CardDescription`, `CardContent`, and `CardFooter` components in `card.tsx`.
>   - **Routing**:
>     - Updates `routes.ts` to include the new home page route at `/`.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=tensorzero%2Ftensorzero&utm_source=github&utm_medium=referral)<sup> for 98fbf8ed559633ccff362ced78427f4b75268dda. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by GabrielBianconi** [comment]
Hi @ChetanXpro - thanks for the contribution!

Could you update the PR to match the [v0.dev mockup](https://v0.dev/chat/MjOv5O0HwV9?b=b_vwIdC2Dh2Dd) more closely?

In v0, if you close the preview and check the `Code` tab, it'll already have all the UI code in there. We only need to migrate it to our dashboard. But using that should ensure it matches the design exactly.

Thanks!

**Review by GabrielBianconi — CHANGES_REQUESTED** [review]
Hi @ChetanXpro - thanks for the contribution!

Could you update the PR to match the [v0.dev mockup](https://v0.dev/chat/MjOv5O0HwV9?b=b_vwIdC2Dh2Dd) more closely?

In v0, if you close the preview and check the `Code` tab, it'll already have all the UI code in there. We only need to migrate it to our dashboard. But using that should ensure it matches the design exactly.

Thanks!

**Comment by ChetanXpro** [comment]
Hey @GabrielBianconi , I've used the v0 code as suggested, could you please check if this looks okay?

Screenshot 2024-12-30 at 1 46 51 PM

**Comment by GabrielBianconi** [comment]
Hi @ChetanXpro - I think you forgot to push your latest changes :)

**Comment by ChetanXpro** [comment]
@GabrielBianconi my bad, I forgot to push the commit. I just pushed it now.

**Comment by GabrielBianconi** [comment]
Thanks @ChetanXpro, looks great! I only made some minor CSS changes. We can merge, @virajmehta you need to approve now.

**Review by virajmehta — APPROVED** [review]

**Review by GabrielBianconi — APPROVED** [review]

**Pull request merged**
