### PR TITLE
add support for xai

### PR DESCRIPTION
**Pull request by Kaboomtastic**
> [!IMPORTANT]
> Add support for XAI inference provider with error handling, configuration, and tests.
> 
>   - **Behavior**:
>     - Adds `XAIProvider` in `xai.rs` for handling inference requests.
>     - Supports standard and streaming inference methods.
>     - Handles XAI-specific errors with `ErrorDetails::XAIClient` and `ErrorDetails::XAIServer` in `error.rs`.
>   - **Configuration**:
>     - Updates `ProviderConfig` in `model.rs` to include XAI.
>     - Adds XAI model configurations in `tensorzero.toml`.
>   - **Testing**:
>     - Adds end-to-end tests for XAI in `xai.rs` and `mod.rs` under `tests/e2e/providers`.
>     - Updates `nextest.toml` to run XAI E2E tests sequentially.
>   - **Misc**:
>     - Adds `XAI_API_KEY` to `merge-queue.yml` for E2E tests.
>     - Adds `README.md`, `tensorzero.toml`, and `docker-compose.yml` for XAI examples.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=tensorzero%2Ftensorzero&utm_source=github&utm_medium=referral)<sup> for 50de064d3b502866d247bcb07bed4035216eee3b. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by GabrielBianconi** [comment]
Hi @Kaboomtastic - thank you for the contribution!

I haven't carefully reviewed the code yet but superficially it looks good! The only missing piece is including xAI in our E2E tests (`gateway/tests/e2e/providers`). Would you be able to add them? We'd be happy to help or take it from here otherwise, let us know.

I'll generate an xAI API key (which will be available as `XAI_API_KEY`) for the associated GitHub Action (& confirm everything works from our side as well).

Thanks again for the contribution!

**Comment by Kaboomtastic** [comment]
Hi @GabrielBianconi !

I'd be happy to add the tests! Thank you for pointing that part out. I'm still getting familiar with the repo and figured I was missing something. I'll try and get it done and ready for review sometime tomorrow.

**Comment by Kaboomtastic** [comment]
Didn't realize that `start_batch_inference` was added to the `Inference Provider` trait so working on that now

**Comment by GabrielBianconi** [comment]
* Made some changes to E2E tests for the xAI provider. While doing so, I found two bugs in the xAI API [[1]](https://gist.github.com/GabrielBianconi/47a4247cfd8b6689e7228f654806272d) [[2]](https://gist.github.com/GabrielBianconi/2199022d0ea8518e06d366fb613c5bb5). We've reported them to the xAI team. We've disabled/documented the relevant tests.
* Added a provider guide example.
* Added the corresponding documentation to our website [[docs PR (private for now)]](https://github.com/tensorzero/www/pull/102).

**Comment by GabrielBianconi** [comment]
@ellipsis-dev please review

**Review by GabrielBianconi — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
