### PR TITLE
feat: add stream example for inference

### LINKED ISSUE #304: Add an example that uses streaming inference

### PR DESCRIPTION
**Pull request by vincent0426**
Closes #304

----

> [!IMPORTANT]
> Adds `simple-chatbot-stream.py` example for streaming inference with `AsyncTensorZeroGateway`.
> 
>   - **New Example Script**:
>     - Adds `simple-chatbot-stream.py` in `examples/tutorial/01-simple-chatbot/`.
>     - Demonstrates streaming inference using `AsyncTensorZeroGateway`.
>   - **Functionality**:
>     - Connects to gateway URL from `TENSORZERO_GATEWAY_URL` environment variable or defaults to `http://localhost:3000`.
>     - Sends a message to `mischievous_chatbot` function and prints response chunks.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=tensorzero%2Ftensorzero&utm_source=github&utm_medium=referral)<sup> for c6dd5f184e19e26eabf50036e0d74f722688151b. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by GabrielBianconi** [comment]
Thank you for the contribution @vincent0426. I moved it to a different location and made some adjustments. We'll publish an associated guide in the docs soon.

**Review by GabrielBianconi — APPROVED** [review]

**Review by virajmehta — APPROVED** [review]
LGTM, thanks @vincent0426!

**Comment by GabrielBianconi** [comment]
recheck

**Comment by vincent0426** [comment]
I have read the Contributor License Agreement (CLA) and hereby sign the CLA.

**Pull request merged**
